// Auto-generated gallery content from ReservasImages/INDEX.md
export interface ReservasGalleryItem {
  id: number
  filename: string
  src: string
  category: 'cliente' | 'whatsapp' | 'admin' | 'ia'
  categoryLabel: string
  theme: 'light' | 'dark'
  title: string
  metric: string
  tag: string
}

export const reservasGalleryItems: ReservasGalleryItem[] = [
  {
    "id": 1,
    "filename": "01_hero_reservas_solo_con_numero.png",
    "src": "/ReservasImages/01_hero_reservas_solo_con_numero.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "Su cliente agenda en 30 segundos. Sin crear cuentas. Sin contraseñas.",
    "metric": "-85% Fricción",
    "tag": "SOLO CON EL NÚMERO"
  },
  {
    "id": 2,
    "filename": "02_experiencia_cero_friccion_30_segundos.png",
    "src": "/ReservasImages/02_experiencia_cero_friccion_30_segundos.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "De abrir el link a cita confirmada en exactamente 30 segundos.",
    "metric": "30 Segundos",
    "tag": "VELOCIDAD DE RESERVA"
  },
  {
    "id": 3,
    "filename": "03_reconocimiento_inteligente_por_telefono.png",
    "src": "/ReservasImages/03_reconocimiento_inteligente_por_telefono.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "El sistema reconoce al cliente habitual apenas introduce su teléfono.",
    "metric": "+40% Fidelización",
    "tag": "CLIENTE RECURRENTE"
  },
  {
    "id": 4,
    "filename": "04_comparativa_con_registro_vs_solo_numero.png",
    "src": "/ReservasImages/04_comparativa_con_registro_vs_solo_numero.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "Software Tradicional vs SoftRent: Por qué la gente abandona su agenda.",
    "metric": "+55% Citas",
    "tag": "COMPARATIVA DIRECTA"
  },
  {
    "id": 5,
    "filename": "05_flujo_ultra_rapido_4_pasos.png",
    "src": "/ReservasImages/05_flujo_ultra_rapido_4_pasos.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "Cuatro decisiones simples. Cero confusión en pantalla.",
    "metric": "4 Pasos",
    "tag": "FLUJO VISUAL EN 4 PASOS"
  },
  {
    "id": 6,
    "filename": "06_maxima_conversion_cero_abandono.png",
    "src": "/ReservasImages/06_maxima_conversion_cero_abandono.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "Transforme el 94% de sus visitas en citas reales en su local.",
    "metric": "94% Éxito",
    "tag": "CONVERSIÓN COMERCIAL"
  },
  {
    "id": 7,
    "filename": "07_seguridad_privacidad_verificacion_sms.png",
    "src": "/ReservasImages/07_seguridad_privacidad_verificacion_sms.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "Privacidad blindada y verificación directa por WhatsApp oficial.",
    "metric": "100% Seguro",
    "tag": "SEGURIDAD LOCAL"
  },
  {
    "id": 8,
    "filename": "08_comprobante_digital_confirmacion_inmediata.png",
    "src": "/ReservasImages/08_comprobante_digital_confirmacion_inmediata.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "Comprobante digital inmediato: En pantalla y directo al WhatsApp.",
    "metric": "1 Clic Waze",
    "tag": "COMPROBANTE AL INSTANTE"
  },
  {
    "id": 9,
    "filename": "09_asistente_ia_whatsapp_24_7.png",
    "src": "/ReservasImages/09_asistente_ia_whatsapp_24_7.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "Su negocio atiende a las 11:45 PM mientras usted está descansando.",
    "metric": "0.4s Latencia",
    "tag": "IA INTEGRADA 24/7"
  },
  {
    "id": 10,
    "filename": "10_conversacion_natural_agendamiento_bot.png",
    "src": "/ReservasImages/10_conversacion_natural_agendamiento_bot.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "Una IA que habla como una persona, no como un menú numérico aburrido.",
    "metric": "100% Natural",
    "tag": "CONVERSACIÓN NATURAL"
  },
  {
    "id": 11,
    "filename": "11_ia_recomendacion_servicios_contextual.png",
    "src": "/ReservasImages/11_ia_recomendacion_servicios_contextual.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "La IA recomienda servicios complementarios y sube el ticket promedio.",
    "metric": "+25% Ticket",
    "tag": "VENTA CRUZADA INTELIGENTE"
  },
  {
    "id": 12,
    "filename": "12_sincronizacion_tiempo_real_bot_y_web.png",
    "src": "/ReservasImages/12_sincronizacion_tiempo_real_bot_y_web.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "Lo que se agenda en WhatsApp aparece al instante en la Web.",
    "metric": "100ms Sync",
    "tag": "SINCRONIZACIÓN TOTAL"
  },
  {
    "id": 13,
    "filename": "13_ia_preguntas_frecuentes_ubicacion_precios.png",
    "src": "/ReservasImages/13_ia_preguntas_frecuentes_ubicacion_precios.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "Resuelve dudas de ubicación, parqueo y precios sin que usted toque el celular.",
    "metric": "3h Ahorradas",
    "tag": "RESOLUCIÓN AUTOMÁTICA"
  },
  {
    "id": 14,
    "filename": "14_ia_tono_amigable_costarricense.png",
    "src": "/ReservasImages/14_ia_tono_amigable_costarricense.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "Entrenada para el trato tico: Cálido, respetuoso y con identidad local.",
    "metric": "100% Tico",
    "tag": "TONO LOCAL COSTARRICENSE"
  },
  {
    "id": 15,
    "filename": "15_ia_deteccion_conflictos_horarios_alternativos.png",
    "src": "/ReservasImages/15_ia_deteccion_conflictos_horarios_alternativos.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "¿Horario lleno? La IA ofrece las dos alternativas más cercanas.",
    "metric": "0 Huecos",
    "tag": "GESTIÓN DE CONFLICTOS"
  },
  {
    "id": 16,
    "filename": "16_ia_lectura_comprobantes_sinpe_movil.png",
    "src": "/ReservasImages/16_ia_lectura_comprobantes_sinpe_movil.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "La IA lee y valida los comprobantes de SINPE Móvil automáticamente.",
    "metric": "100% Seguro",
    "tag": "VISIÓN ARTIFICIAL"
  },
  {
    "id": 17,
    "filename": "17_paso1_seleccion_profesional_especialista.png",
    "src": "/ReservasImages/17_paso1_seleccion_profesional_especialista.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "Paso 1: El cliente elige a su barbero o especialista de confianza.",
    "metric": "Paso 01",
    "tag": "PASO 1: PROFESIONAL"
  },
  {
    "id": 18,
    "filename": "18_paso2_catalogo_servicios_precios_colones.png",
    "src": "/ReservasImages/18_paso2_catalogo_servicios_precios_colones.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "Paso 2: Catálogo con precios en colones y tiempos de servicio exactos.",
    "metric": "Paso 02",
    "tag": "PASO 2: SERVICIOS"
  },
  {
    "id": 19,
    "filename": "19_paso3_calendario_slots_tiempo_real.png",
    "src": "/ReservasImages/19_paso3_calendario_slots_tiempo_real.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "Paso 3: Ranuras horarias libres calculadas en tiempo real.",
    "metric": "Paso 03",
    "tag": "PASO 3: CALENDARIO"
  },
  {
    "id": 20,
    "filename": "20_paso4_datos_cliente_solo_numero.png",
    "src": "/ReservasImages/20_paso4_datos_cliente_solo_numero.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "Paso 4: Solo dos campos. Teléfono, Nombre y Confirmar.",
    "metric": "Paso 04",
    "tag": "PASO 4: DATOS MÍNIMOS"
  },
  {
    "id": 21,
    "filename": "21_transparencia_precios_duracion_servicios.png",
    "src": "/ReservasImages/21_transparencia_precios_duracion_servicios.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "Precios transparentes y sin sorpresas para ganar la lealtad del cliente.",
    "metric": "₡ Colones",
    "tag": "CONFIANZA TOTAL"
  },
  {
    "id": 22,
    "filename": "22_perfil_profesional_foto_y_especialidad.png",
    "src": "/ReservasImages/22_perfil_profesional_foto_y_especialidad.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "Destaque el talento de su equipo con tarjetas individuales de presentación.",
    "metric": "Top Nivel",
    "tag": "MARCA PERSONAL"
  },
  {
    "id": 23,
    "filename": "23_calculo_inteligente_duracion_multiple.png",
    "src": "/ReservasImages/23_calculo_inteligente_duracion_multiple.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "light",
    "title": "Cálculo inteligente de tiempos cuando el cliente suma varios servicios.",
    "metric": "1h 25m",
    "tag": "TIEMPOS COMBINADOS"
  },
  {
    "id": 24,
    "filename": "24_resumen_cita_google_calendar_whatsapp.png",
    "src": "/ReservasImages/24_resumen_cita_google_calendar_whatsapp.png",
    "category": "cliente",
    "categoryLabel": "Reserva Sin Contraseña",
    "theme": "dark",
    "title": "Un clic para agregar a Google Calendar y Apple Calendar en el móvil.",
    "metric": "1 Toque",
    "tag": "INTEGRACIÓN DE CALENDARIO"
  },
  {
    "id": 25,
    "filename": "25_recordatorio_automatico_24_horas_antes.png",
    "src": "/ReservasImages/25_recordatorio_automatico_24_horas_antes.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "light",
    "title": "Recordatorio automático 24 horas antes: El 85% de las ausencias se evitan aquí.",
    "metric": "-85% Ausencias",
    "tag": "RECORDATORIO 24 HORAS"
  },
  {
    "id": 26,
    "filename": "26_alerta_urgente_2_horas_antes_confirmacion.png",
    "src": "/ReservasImages/26_alerta_urgente_2_horas_antes_confirmacion.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "dark",
    "title": "Aviso 2 horas antes de la cita: 'Luis, te esperamos a las 3:00 PM'.",
    "metric": "100% Puntual",
    "tag": "ALERTA ÚLTIMA HORA"
  },
  {
    "id": 27,
    "filename": "27_reprogramacion_cancelacion_un_click.png",
    "src": "/ReservasImages/27_reprogramacion_cancelacion_un_click.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "light",
    "title": "Reprogramación y cancelación en 1 clic sin discusiones ni llamadas incómodas.",
    "metric": "1 Clic",
    "tag": "REPROGRAMACIÓN FÁCIL"
  },
  {
    "id": 28,
    "filename": "28_reactivacion_automatica_clientes_inactivos.png",
    "src": "/ReservasImages/28_reactivacion_automatica_clientes_inactivos.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "dark",
    "title": "La IA detecta clientes inactivos y les envía una invitación a volver.",
    "metric": "+30% Recompra",
    "tag": "REACTIVACIÓN DE CLIENTES"
  },
  {
    "id": 29,
    "filename": "29_lista_espera_inteligente_huecos_libres.png",
    "src": "/ReservasImages/29_lista_espera_inteligente_huecos_libres.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "light",
    "title": "Lista de espera inteligente: Llene cancelaciones en 3 minutos.",
    "metric": "3 Minutos",
    "tag": "LISTA DE ESPERA"
  },
  {
    "id": 30,
    "filename": "30_reduccion_ausencias_impacto_financiero.png",
    "src": "/ReservasImages/30_reduccion_ausencias_impacto_financiero.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "dark",
    "title": "Deje de perder ₡180.000 al mes por clientes que olvidaron su cita.",
    "metric": "₡180.000/mes",
    "tag": "IMPACTO FINANCIERO"
  },
  {
    "id": 31,
    "filename": "31_congelar_cita_abono_sinpe_movil.png",
    "src": "/ReservasImages/31_congelar_cita_abono_sinpe_movil.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "light",
    "title": "Congela la cita con un abono previo: Adiós definitivo a reservas falsas.",
    "metric": "50% Abono",
    "tag": "ABONO POR SINPE"
  },
  {
    "id": 32,
    "filename": "32_instrucciones_claras_pago_sinpe.png",
    "src": "/ReservasImages/32_instrucciones_claras_pago_sinpe.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "dark",
    "title": "Pantalla con teléfono y botón 'Copiar número SINPE' en un toque.",
    "metric": "Copiar Fácil",
    "tag": "INSTRUCCIONES DE PAGO"
  },
  {
    "id": 33,
    "filename": "33_verificacion_referencia_sinpe_hacienda.png",
    "src": "/ReservasImages/33_verificacion_referencia_sinpe_hacienda.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "light",
    "title": "Registro exacto del número de referencia de transferencia bancaria.",
    "metric": "Referencia #",
    "tag": "REGISTRO DE REFERENCIA"
  },
  {
    "id": 34,
    "filename": "34_facturacion_electronica_automatica_cierre.png",
    "src": "/ReservasImages/34_facturacion_electronica_automatica_cierre.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "dark",
    "title": "Facturación electrónica automática al cierre de cada visita.",
    "metric": "Hacienda v4.3",
    "tag": "FACTURA ELECTRÓNICA"
  },
  {
    "id": 35,
    "filename": "35_cierre_caja_diario_sin_papel.png",
    "src": "/ReservasImages/35_cierre_caja_diario_sin_papel.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "light",
    "title": "Arqueo de caja automático al cierre: SINPE Móvil, efectivo y total cobrado.",
    "metric": "Cero Papel",
    "tag": "CIERRE DE CAJA DIARIO"
  },
  {
    "id": 36,
    "filename": "36_reporte_financiero_ingresos_sinpe_vs_efectivo.png",
    "src": "/ReservasImages/36_reporte_financiero_ingresos_sinpe_vs_efectivo.png",
    "category": "whatsapp",
    "categoryLabel": "WhatsApp & SINPE",
    "theme": "dark",
    "title": "Reportes claros de rendimiento: Qué servicios y profesionales rinden más.",
    "metric": "Datos Reales",
    "tag": "REPORTES FINANCIEROS"
  },
  {
    "id": 37,
    "filename": "37_dashboard_dueno_agenda_diaria.png",
    "src": "/ReservasImages/37_dashboard_dueno_agenda_diaria.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "light",
    "title": "El centro de mando de su negocio: Todas las citas de hoy en una sola pantalla.",
    "metric": "14 Citas Hoy",
    "tag": "DASHBOARD EJECUTIVO"
  },
  {
    "id": 38,
    "filename": "38_gestion_empleados_turnos_dias_libres.png",
    "src": "/ReservasImages/38_gestion_empleados_turnos_dias_libres.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "dark",
    "title": "Control flexible de horarios, turnos y días libres para cada empleado.",
    "metric": "Turnos Claros",
    "tag": "GESTIÓN DE EQUIPO"
  },
  {
    "id": 39,
    "filename": "39_catalogo_servicios_edicion_precios.png",
    "src": "/ReservasImages/39_catalogo_servicios_edicion_precios.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "light",
    "title": "Agregue o cambie precios de servicios en menos de 10 segundos.",
    "metric": "10 Segundos",
    "tag": "EDICIÓN DE SERVICIOS"
  },
  {
    "id": 40,
    "filename": "40_galeria_trabajos_portafolio_fotos.png",
    "src": "/ReservasImages/40_galeria_trabajos_portafolio_fotos.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "dark",
    "title": "Galería de fotos de sus mejores trabajos para enamorar al cliente antes de reservar.",
    "metric": "Fotos HD",
    "tag": "PORTAFOLIO VISUAL"
  },
  {
    "id": 41,
    "filename": "41_directorio_clientes_historial_visitas.png",
    "src": "/ReservasImages/41_directorio_clientes_historial_visitas.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "light",
    "title": "Ficha completa de cada cliente: Historial, cumpleaños, notas y preferencias.",
    "metric": "Historial VIP",
    "tag": "CRM DE CLIENTES"
  },
  {
    "id": 42,
    "filename": "42_bloqueo_anti_sobreventa_agenda_blindada.png",
    "src": "/ReservasImages/42_bloqueo_anti_sobreventa_agenda_blindada.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "dark",
    "title": "Bloqueo anti-sobreventa garantizado: Cero citas cruzadas o agendadas dos veces.",
    "metric": "100% Blindado",
    "tag": "AGENDA BLINDADA"
  },
  {
    "id": 43,
    "filename": "43_vista_movil_barbero_especialista.png",
    "src": "/ReservasImages/43_vista_movil_barbero_especialista.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "light",
    "title": "Cada profesional ve solo su agenda desde su celular personal.",
    "metric": "App Staff",
    "tag": "VISTA PARA EL STAFF"
  },
  {
    "id": 44,
    "filename": "44_interfaz_modo_claro_y_oscuro_comercial.png",
    "src": "/ReservasImages/44_interfaz_modo_claro_y_oscuro_comercial.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "dark",
    "title": "Modo Claro y Oscuro adaptativo: Diseñado para verse espectacular en su local.",
    "metric": "Dark / Light",
    "tag": "MODO CLARO Y OSCURO"
  },
  {
    "id": 45,
    "filename": "45_vertical_barberias_salones_belleza.png",
    "src": "/ReservasImages/45_vertical_barberias_salones_belleza.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "light",
    "title": "Especializado en Barberías & Salones: Agenda por sillón y cobro de abonos.",
    "metric": "Barberías CR",
    "tag": "VERTICAL BARBERÍAS"
  },
  {
    "id": 46,
    "filename": "46_vertical_clinicas_veterinarias_grooming.png",
    "src": "/ReservasImages/46_vertical_clinicas_veterinarias_grooming.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "dark",
    "title": "Especializado en Veterinarias & Grooming: Citas médicas y baños caninos organizados.",
    "metric": "Veterinarias",
    "tag": "VERTICAL VETERINARIAS"
  },
  {
    "id": 47,
    "filename": "47_vertical_estudios_tatuaje_arte_corporal.png",
    "src": "/ReservasImages/47_vertical_estudios_tatuaje_arte_corporal.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "light",
    "title": "Especializado en Tatuajes & Piercing: Cobro de abono de diseño obligatorio.",
    "metric": "Tattoo Studios",
    "tag": "VERTICAL TATUAJES"
  },
  {
    "id": 48,
    "filename": "48_vertical_consultorios_fisioterapia_estetica.png",
    "src": "/ReservasImages/48_vertical_consultorios_fisioterapia_estetica.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "dark",
    "title": "Especializado en Clínicas & Fisioterapia: Trato profesional y confirmación médica.",
    "metric": "Consultorios",
    "tag": "VERTICAL CONSULTORIOS"
  },
  {
    "id": 49,
    "filename": "49_garantia_despliegue_48_horas_costa_rica.png",
    "src": "/ReservasImages/49_garantia_despliegue_48_horas_costa_rica.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "light",
    "title": "En marcha en 48 horas en Costa Rica: Nosotros configuramos todo por usted.",
    "metric": "48 Horas",
    "tag": "INSTALACIÓN LLAVE EN MANO"
  },
  {
    "id": 50,
    "filename": "50_ecosistema_completo_softrent_citas.png",
    "src": "/ReservasImages/50_ecosistema_completo_softrent_citas.png",
    "category": "admin",
    "categoryLabel": "Gestión & Verticales",
    "theme": "dark",
    "title": "El Ecosistema Completo SoftRent Citas: Web + WhatsApp + SINPE + IA.",
    "metric": "Todo en Uno",
    "tag": "ECOSISTEMA INTEGRAL"
  },
  {
    "id": 51,
    "filename": "51_admin_panel_conocimiento_ia_cerebro.png",
    "src": "/ReservasImages/51_admin_panel_conocimiento_ia_cerebro.png",
    "category": "ia",
    "categoryLabel": "Cerebro IA & RAG",
    "theme": "light",
    "title": "El cerebro de su asistente virtual: Usted enseña sin saber de código.",
    "metric": "14 Documentos",
    "tag": "IA KNOWLEDGE BASE"
  },
  {
    "id": 52,
    "filename": "52_admin_ia_busqueda_semantica_vectores.png",
    "src": "/ReservasImages/52_admin_ia_busqueda_semantica_vectores.png",
    "category": "ia",
    "categoryLabel": "Cerebro IA & RAG",
    "theme": "dark",
    "title": "La IA busca por significado real, no solo por palabras exactas.",
    "metric": "0 Alucinaciones",
    "tag": "BÚSQUEDA HÍBRIDA RAG"
  },
  {
    "id": 53,
    "filename": "53_admin_ia_consola_prueba_preguntas.png",
    "src": "/ReservasImages/53_admin_ia_consola_prueba_preguntas.png",
    "category": "ia",
    "categoryLabel": "Cerebro IA & RAG",
    "theme": "light",
    "title": "Pruebe preguntas en vivo antes de que salgan a WhatsApp.",
    "metric": "Test en Vivo",
    "tag": "CONSOLA DE PRUEBAS"
  },
  {
    "id": 54,
    "filename": "54_admin_ia_ingesta_automatica_catalogo.png",
    "src": "/ReservasImages/54_admin_ia_ingesta_automatica_catalogo.png",
    "category": "ia",
    "categoryLabel": "Cerebro IA & RAG",
    "theme": "dark",
    "title": "Servicios, horarios y staff: La IA aprende de su catálogo sola.",
    "metric": "100% Automático",
    "tag": "INGESTA AUTOMÁTICA"
  },
  {
    "id": 55,
    "filename": "55_admin_ia_monitor_estado_indice.png",
    "src": "/ReservasImages/55_admin_ia_monitor_estado_indice.png",
    "category": "ia",
    "categoryLabel": "Cerebro IA & RAG",
    "theme": "light",
    "title": "Estado del índice vectorial: Documentos activos, partes y cálculo.",
    "metric": "48 Partes",
    "tag": "MONITOR DE EMBEDDINGS"
  },
  {
    "id": 56,
    "filename": "56_admin_ia_filtro_privacidad_datos.png",
    "src": "/ReservasImages/56_admin_ia_filtro_privacidad_datos.png",
    "category": "ia",
    "categoryLabel": "Cerebro IA & RAG",
    "theme": "dark",
    "title": "Filtro inteligente de privacidad: Cero fuga de datos personales.",
    "metric": "100% Blindado",
    "tag": "PROTECCIÓN DE PRIVACIDAD"
  },
  {
    "id": 57,
    "filename": "57_admin_ia_politicas_tolerancia_faq.png",
    "src": "/ReservasImages/57_admin_ia_politicas_tolerancia_faq.png",
    "category": "ia",
    "categoryLabel": "Cerebro IA & RAG",
    "theme": "light",
    "title": "Políticas de tolerancia, parqueo y métodos de pago explicadas con calma.",
    "metric": "Reglas Claras",
    "tag": "POLÍTICAS Y FAQS"
  },
  {
    "id": 58,
    "filename": "58_admin_agenda_operativa_diaria.png",
    "src": "/ReservasImages/58_admin_agenda_operativa_diaria.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "dark",
    "title": "La pantalla de trabajo del staff: Atender el día sin pantallas complejas.",
    "metric": "14 Citas Hoy",
    "tag": "AGENDA DE TRABAJO"
  },
  {
    "id": 59,
    "filename": "59_admin_agenda_cambio_estado_un_toque.png",
    "src": "/ReservasImages/59_admin_agenda_cambio_estado_un_toque.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "light",
    "title": "Cambio de estado en un solo toque: Confirmar, Atender o Cancelar.",
    "metric": "1 Toque",
    "tag": "CONTROL DE ESTADOS"
  },
  {
    "id": 60,
    "filename": "60_admin_agenda_filtro_multiprofesional.png",
    "src": "/ReservasImages/60_admin_agenda_filtro_multiprofesional.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "dark",
    "title": "Monitoree todos los sillones o filtre por profesional específico.",
    "metric": "Multi-Sillón",
    "tag": "VISTA MULTIPROFESIONAL"
  },
  {
    "id": 61,
    "filename": "61_admin_agenda_alertas_puntualidad.png",
    "src": "/ReservasImages/61_admin_agenda_alertas_puntualidad.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "light",
    "title": "Indicadores visuales de citas: Quién ya llegó y quién viene en camino.",
    "metric": "Puntualidad",
    "tag": "ALERTAS DE LLEGADA"
  },
  {
    "id": 62,
    "filename": "62_admin_servicios_editor_maestro.png",
    "src": "/ReservasImages/62_admin_servicios_editor_maestro.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "dark",
    "title": "Modifique precios y duraciones en menos de 5 segundos.",
    "metric": "5 Segundos",
    "tag": "CATÁLOGO DE SERVICIOS"
  },
  {
    "id": 63,
    "filename": "63_admin_adicionales_motor_upselling.png",
    "src": "/ReservasImages/63_admin_adicionales_motor_upselling.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "light",
    "title": "Motor de adicionales: Aumente el ticket promedio de su local.",
    "metric": "+30% Ingresos",
    "tag": "VENTA CRUZADA UPSELLING"
  },
  {
    "id": 64,
    "filename": "64_admin_servicios_asignacion_profesional.png",
    "src": "/ReservasImages/64_admin_servicios_asignacion_profesional.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "dark",
    "title": "Asigne qué profesionales están capacitados para cada servicio.",
    "metric": "Skills Match",
    "tag": "ASIGNACIÓN POR SKILLS"
  },
  {
    "id": 65,
    "filename": "65_admin_servicios_pausa_inmediata.png",
    "src": "/ReservasImages/65_admin_servicios_pausa_inmediata.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "light",
    "title": "Oculte o pause servicios en 1 clic sin borrarlos de su base de datos.",
    "metric": "Switch On/Off",
    "tag": "PAUSA RÁPIDA DE SERVICIOS"
  },
  {
    "id": 66,
    "filename": "66_admin_empleados_directorio_staff.png",
    "src": "/ReservasImages/66_admin_empleados_directorio_staff.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "dark",
    "title": "Perfiles del staff con fotografía, especialidad y estado activo.",
    "metric": "Staff Activo",
    "tag": "DIRECTORIO DE EQUIPO"
  },
  {
    "id": 67,
    "filename": "67_admin_horarios_turnos_flexibles.png",
    "src": "/ReservasImages/67_admin_horarios_turnos_flexibles.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "light",
    "title": "Horarios flexibles por empleado: Mañanas, tardes o turnos rotativos.",
    "metric": "Turnos Claros",
    "tag": "TURNOS Y HORARIOS"
  },
  {
    "id": 68,
    "filename": "68_admin_horarios_blindaje_almuerzo.png",
    "src": "/ReservasImages/68_admin_horarios_blindaje_almuerzo.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "dark",
    "title": "Blindaje de horas de almuerzo: Su equipo descansa sin interrupciones.",
    "metric": "1h Almuerzo",
    "tag": "PAUSAS Y ALMUERZOS"
  },
  {
    "id": 69,
    "filename": "69_admin_horarios_dias_libres_vacaciones.png",
    "src": "/ReservasImages/69_admin_horarios_dias_libres_vacaciones.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "light",
    "title": "Gestión de días libres y vacaciones con bloqueo anticipado en la web.",
    "metric": "Días Libres",
    "tag": "DÍAS LIBRES Y FERIADOS"
  },
  {
    "id": 70,
    "filename": "70_admin_restricciones_cierres_nacionales.png",
    "src": "/ReservasImages/70_admin_restricciones_cierres_nacionales.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "dark",
    "title": "Bloqueo por feriados nacionales o cierres por mantenimiento.",
    "metric": "Feriados CR",
    "tag": "CIERRES Y FERIADOS"
  },
  {
    "id": 71,
    "filename": "71_admin_productos_inventario_retail.png",
    "src": "/ReservasImages/71_admin_productos_inventario_retail.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "light",
    "title": "Control de venta de productos físicos en el mostrador de su local.",
    "metric": "Venta Retail",
    "tag": "INVENTARIO RETAIL"
  },
  {
    "id": 72,
    "filename": "72_admin_citas_buscador_avanzado.png",
    "src": "/ReservasImages/72_admin_citas_buscador_avanzado.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "dark",
    "title": "Historial y búsqueda de citas: Encuentre cualquier registro en segundos.",
    "metric": "Buscador Veloz",
    "tag": "BUSCADOR DE CITAS"
  },
  {
    "id": 73,
    "filename": "73_admin_seguridad_autenticacion_telefono.png",
    "src": "/ReservasImages/73_admin_seguridad_autenticacion_telefono.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "light",
    "title": "Autenticación corporativa: El teléfono es la credencial segura.",
    "metric": "JWT Seguro",
    "tag": "SEGURIDAD POR TELÉFONO"
  },
  {
    "id": 74,
    "filename": "74_admin_cierre_caja_arqueo_diario.png",
    "src": "/ReservasImages/74_admin_cierre_caja_arqueo_diario.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "dark",
    "title": "Cruce de caja automático: SINPE Móvil, efectivo y facturas fiscales.",
    "metric": "Caja Cuadrada",
    "tag": "ARQUEO DE CAJA DIARIO"
  },
  {
    "id": 75,
    "filename": "75_admin_ecosistema_operativo_total.png",
    "src": "/ReservasImages/75_admin_ecosistema_operativo_total.png",
    "category": "admin",
    "categoryLabel": "Agenda & Staff Operativo",
    "theme": "light",
    "title": "SoftRent Citas: El Sistema Operativo definitivo para negocios de servicios.",
    "metric": "Todo en Uno",
    "tag": "SISTEMA OPERATIVO TOTAL"
  }
];
